// src/ai/flows/get-trending-products.ts
'use server';
/**
 * @fileOverview Generates a list of currently trending products by analyzing social media data.
 *
 * - getTrendingProducts - A function that generates a list of trending products.
 * - TrendingProductsOutput - The return type for the getTrendingProducts function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import type { Product, SocialPlatform } from '@/lib/types';
import fetch from 'node-fetch';
import { getRedditAccessToken } from '@/services/reddit-auth';  // ✅ NEW IMPORT

const ProductReviewSchema = z.object({
  platform: z.enum(['Twitter', 'Reddit']).describe("The social media platform (e.g., 'Twitter', 'Reddit')."),
  text: z.string().describe("The full text of the social media post."),
  username: z.string().describe("The username of the author of the post."),
  postUrl: z.string().describe("The direct URL to the social media post."),
});

const fetchTwitterData = async (query: string) => {
  const bearerToken = process.env.X_BEARER_TOKEN;
  console.log("Loaded X_BEARER_TOKEN:", bearerToken);
  if (!bearerToken) {
    console.warn(`X_BEARER_TOKEN not found for query "${query}". Returning empty array.`);
    return [];
  }

  const url = `https://api.twitter.com/2/tweets/search/recent?query=${encodeURIComponent(query)}&tweet.fields=text,author_id,id&expansions=author_id&max_results=10`;

  try {
    const response = await fetch(url, { headers: { 'Authorization': `Bearer ${bearerToken}` } });
    const data: any = await response.json();

    if (!response.ok || !data.data) {
      console.error(`Failed to fetch Twitter data for "${query}":`, data.errors?.[0]?.message || 'Unknown error');
      return [];
    }

    const users = new Map(data.includes?.users?.map((user: any) => [user.id, user.username]) || []);

    return data.data.map((tweet: any) => ({
      platform: 'Twitter' as const,
      text: tweet.text || '',
      username: users.get(tweet.author_id) || 'twitter_user',
      postUrl: `https://twitter.com/${users.get(tweet.author_id) || 'i'}/status/${tweet.id}`,
    }));
  } catch (error) {
    console.error(`Error fetching Twitter data for "${query}":`, error);
    return [];
  }
};

const fetchRedditData = async (query: string) => {
  const bearerToken = await getRedditAccessToken();
  if (!bearerToken) {
    console.warn(`Failed to get Reddit bearer token for query "${query}". Returning empty array.`);
    return [];
  }

  const url = `https://oauth.reddit.com/search?q=${encodeURIComponent(query)}&limit=5&sort=hot`;
  try {
    const response = await fetch(url, {
      headers: {
        'Authorization': `Bearer ${bearerToken}`,
        'User-Agent': 'TrendSense/0.1 by karthiksai12'   // replace 'yourusername' with your Reddit app username
      }
    });

    if (!response.ok) {
      console.error('Failed to fetch Reddit data:', response.statusText);
      return [];
    }

    const data: any = await response.json();
    if (!data.data || !data.data.children) return [];

    return data.data.children.map((post: any) => ({
      platform: 'Reddit' as const,
      text: post.data.title || '',
      username: post.data.author || 'reddit_user',
      postUrl: `https://www.reddit.com${post.data.permalink || ''}`,
    }));
  } catch (error) {
    console.error(`Error fetching Reddit data for "${query}":`, error);
    return [];
  }
};

const TrendingProductSchema = z.object({
  id: z.string().describe("A unique product ID, e.g., 'prod-001'"),
  name: z.string().describe('The name of the product.'),
  category: z.string().describe('The category the product belongs to.'),
  forecastedDemand: z.number().describe('The estimated weekly demand for this product.'),
  inventoryStatus: z.enum(['Optimal', 'Overstock', 'Understock']).describe('The current inventory status based on the trend.'),
  lastUpdated: z.string().describe("A human-readable string indicating when this data was generated, e.g., 'Just now' for live data or 'Generated by AI' for fallback data."),
  imageUrl: z.string().describe('A valid placeholder image URL from \'https://via.placeholder.com\' with a size of 64x64. Use the format https://via.placeholder.com/64x64.png.'),
  reviews: z.array(ProductReviewSchema).describe("A list of 2-3 of the most representative social media posts that signal this trend.")
});

const TrendingProductsOutputSchema = z.object({
  products: z.array(TrendingProductSchema)
});

export type TrendingProductsOutput = z.infer<typeof TrendingProductsOutputSchema>;

export async function getTrendingProducts(): Promise<Product[]> {
  const result = await trendingProductsFlow();
  return result.products as Product[];
}

const prompt = ai.definePrompt({
  name: 'getTrendingProductsPrompt',
  model: 'googleai/gemini-1.5-flash-latest',
  output: { schema: TrendingProductsOutputSchema },
  prompt: `You are the AI engine for "TrendSense," a real-time demand forecasting platform for Walmart. Your primary function is to analyze social media data to identify viral product trends.

You have been provided with a raw data stream of posts from Twitter and Reddit.

Social Media Data:
{{{socialMediaData}}}

Based on this live data, analyze it to identify up to 10 of the most relevant and impactful product trends for Walmart. A higher mention count with positive sentiment should result in higher demand and an 'Understock' status.

For each of the products you identify, you must provide the following information:
- A unique product ID (e.g., prod-001, prod-002).
- The specific product name.
- A plausible Walmart category (e.g., Home Goods, Electronics, Apparel, Beauty, Groceries, Toys).
- A forecasted weekly demand as a number, reflecting its viral velocity.
- An inventory status: 'Understock' for new, explosive trends; 'Optimal' for established trends; 'Overstock' for fading trends.
- A lastUpdated string. Use 'Just now' as you are analyzing live data.
- A valid placeholder image URL from 'https://placehold.co' with a size of 64x64.
- A list of 2-3 of the most representative "reviews" (social media posts) from the provided data that justify why this product is trending. Each review must include the platform, text, username, and the exact postUrl provided in the source data. You MUST NOT alter the postUrl. Use https://via.placeholder.com/64x64.png for the imageUrl.

Return the list of products in the specified JSON format. You must include reviews for each product.`,
});

const trendingProductsFlow = ai.defineFlow(
  {
    name: 'trendingProductsFlow',
    outputSchema: TrendingProductsOutputSchema,
  },
  async () => {
    const topics = ['air fryer', 'skincare', 'running shoes', 'summer dress', 'gaming keyboard', 'protein powder'];
    let allPosts: any[] = [];

    for (const topic of topics) {
      const [twitter, reddit] = await Promise.all([
        fetchTwitterData(topic),
        fetchRedditData(topic)
      ]);
      allPosts = [...allPosts, ...twitter, ...reddit];
    }

    const uniquePosts = Array.from(new Map(allPosts.map(p => [p.text, p])).values());

    if (uniquePosts.length === 0) {
      console.log("No social media data fetched from Twitter or Reddit. Returning fallback data.");
      return getFallbackProducts();
    }

    const socialMediaData = JSON.stringify(uniquePosts, null, 2);

    console.log("-----BEGIN SOCIAL MEDIA ANALYSIS-----\n");
    console.log(`Sending ${uniquePosts.length} unique posts from Twitter and Reddit to the AI model.\n`);
    console.log("-----END SOCIAL MEDIA ANALYSIS-----\n");

    try {
      const { output } = await prompt({ socialMediaData });
      return output!;
    } catch (error) {
      console.error("AI call failed. Returning fallback data.", error);
      return getFallbackProducts();
    }
  }
);

function getFallbackProducts(): TrendingProductsOutput {
  return {
    products: [
      {
        id: 'fallback-001',
        name: 'e.l.f. Halo Glow Liquid Filter',
        category: 'Beauty',
        forecastedDemand: 2200,
        inventoryStatus: 'Understock',
        lastUpdated: 'Generated by AI',
        imageUrl: 'https://placeholder.com/64x64.png',
        reviews: [
          { platform: 'Reddit', text: 'Heard great things about the e.l.f. Halo Glow Liquid Filter. Anyone tried it?', username: 'BeautyFanatic', postUrl: 'https://www.reddit.com/r/Makeup/comments/example' },
          { platform: 'Twitter', text: 'Obsessed with the glow the @elfcosmetics Halo Glow Liquid Filter gives!', username: 'BeautyReviewer', postUrl: 'https://twitter.com/BeautyReviewer/status/example' }
        ],
      }
      // ... (rest of fallback products unchanged)
    ],
  };
}

